openapi: 3.0.0
info:
  title: Demo Conference API
  description: A sample API with information related to a technical conference.  The
    available resources  include *Speakers*, *Sessions* and *Topics*.  A single
    write operation is available to provide  feedback on a session.
  version: v2
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
paths:
  /sessions:
    get:
      description: A list of sessions.  Optional parameters work as filters to reduce the
        listed sessions.
      operationId: GetSessions
      parameters:
        - name: speakername
          in: query
          schema:
            type: string
        - name: dayno
          in: query
          description: Format - int32.
          schema:
            type: integer
        - name: keyword
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
  "/session/{id}":
    get:
      description: Retreive a representation of a single session by Id
      operationId: GetSession
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
  "/session/{id}/topics":
    get:
      operationId: GetSessionTopics
      description: A list of topics covered by a particular session
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
  "/session/{id}/feedback":
    post:
      description: Retreive a representation of a single session by Id
      operationId: SubmitSession
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
  /speakers:
    get:
      operationId: GetSpeakers
      parameters:
        - name: dayno
          in: query
          description: Format - int32.
          schema:
            type: integer
        - name: speakername
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
  "/speaker/{id}":
    get:
      operationId: GetSpeaker
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
  "/speaker/{id}/sessions":
    get:
      operationId: GetSpeakerSessions
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
  "/speaker/{id}/topics":
    get:
      operationId: GetSpeakerTopics
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
servers:
  - url: http://conferenceapi.azurewebsites.net
  - url: https://conferenceapi.azurewebsites.net
components:
  parameters:
    id:
      name: id
      in: path
      description: Format - int32.
      required: true
      schema:
        type: integer
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query